AUGMENTATION  : True
IMAGE_SIZE    : [224,224,3] # as per the pretrained VGG-16 Net Model
BATCH_SIZE    : 16
INCLUDE_TOP   : False
EPOCHS        : 1
CLASSES       : 2
WEIGHTS       : imagenet
LEARNING_RATE : 0.01
